name: Build Extension Pull Request

on:
  pull_request_target:
    branches:    
      - main
    paths:
      - 'extensions/*/*.json'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
          echo "$JAVA_HOME_17_X64/bin" >> $GITHUB_PATH

      - run: |
          curl -sLO https://download.clojure.org/install/linux-install-1.11.1.1113.sh
          chmod +x linux-install-1.11.1.1113.sh
          sudo ./linux-install-1.11.1.1113.sh

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: clojure -P
        name: Fetch deps

      - name: Build PR Extension
        env:
          PR: ${{ github.event.pull_request.number }}
        run: |
          ./script/prBuild.sh --pr $PR

      - uses: actions/upload-artifact@v3
        with:
          name: checkout
          path: |
            checkout
            !checkout/**/node_modules/*
